# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVEniof6NTjsLdJ1xgFBkZXKydgpaXeK
"""

! sudo apt-get install metis

! pip install Cluster_Ensembles

import numpy as np
import matplotlib.pyplot as plt
from random import choice
import community as cm
import networkx as nx


import Cluster_Ensembles as CE

import pandas as pd 
  
  # reading csv file  
article = pd.read_csv("article.csv", sep="\t")
auteur =  pd.read_csv("auteur.csv", sep = ";")

article.describe()

article.groupby('year').agg('count')

#Supprimer les lignes qui n'ont pas d'abstract
article['abstract'].replace('',np.nan, inplace=True)
article.dropna(subset=['abstract'], inplace = True)

#Supprimer les lignes qui n'ont pas d'affliation
auteur['Affiliation'].replace('',np.nan, inplace=True)
auteur.dropna(subset=['Affiliation'], inplace = True)

article

docAut = pd.DataFrame(np.zeros((article.shape[0],len(auteur["Authors_Name"]))), columns =  auteur["Authors_Name"])

docAut

i=0
for x in article["authors"]:
  print(i)
  for j in x.split(", "):
    print(j)
    if (np.sum(j == auteur["Authors_Name"])>0):
      print("trouvé")
      docAut.ix[i,j] =1 
  i+=1

docAut

docAut.sum()

docAut.to_csv("docAut.csv", sep='\t')



